# Generated by Django 5.0.6 on 2024-06-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.CharField(max_length=30),
        ),
    ]
